volumes:
  env:

services:
  ethrex_l1:
    container_name: ethrex_l1
    image: "ethrex:main"
    build: ../../
    ports:
      - 127.0.0.1:8545:8545
    environment:
      - ETHREX_LOG_LEVEL
    volumes:
      - ../../fixtures/genesis/l1.json:/genesis/l1.json
    command: --network /genesis/l1.json --http.addr 0.0.0.0 --http.port 8545 --dev

  contract_deployer:
    container_name: contract_deployer
    image: "ethrex:main-l2"
    restart: on-failure:10
    build:
      context: ../../
      args:
        - BUILD_FLAGS=--features l2,l2-sql
    volumes:
      # NOTE: DOCKER_ETHREX_WORKDIR is defined in crates/l2/Makefile
      - ./contracts:${DOCKER_ETHREX_WORKDIR}/contracts
      - env:/env/
      - ../../fixtures/genesis/l1.json:${DOCKER_ETHREX_WORKDIR}/fixtures/genesis/l1.json
      - ../../fixtures/genesis/l2.json:${DOCKER_ETHREX_WORKDIR}/fixtures/genesis/l2.json
      - ../../fixtures/keys/private_keys_l1.txt:${DOCKER_ETHREX_WORKDIR}/fixtures/keys/private_keys_l1.txt
      - ../guest-program/bin/sp1/out/:${DOCKER_ETHREX_WORKDIR}/sp1_out
      - ../guest-program/bin/sp1/out/riscv32im-succinct-zkvm-vk-u32:${DOCKER_ETHREX_WORKDIR}/riscv32im-succinct-zkvm-vk-u32
      - ../guest-program/bin/sp1/out/riscv32im-succinct-zkvm-vk-bn254:${DOCKER_ETHREX_WORKDIR}/riscv32im-succinct-zkvm-vk-bn254
      - ../guest-program/bin/risc0/out/riscv32im-risc0-vk:${DOCKER_ETHREX_WORKDIR}/riscv32im-risc0-vk
    environment:
      - ETHREX_ETH_RPC_URL=http://ethrex_l1:8545
      # NOTE: The paths in the env variables must match those
      # specified in the `volumes:` section
      - ETHREX_DEPLOYER_L1_PRIVATE_KEY=${ETHREX_DEPLOYER_PRIVATE_KEY:-0x385c546456b6a603a1cfcaa9ec9494ba4832da08dd6bcf4de9a71e4a01b74924}
      - ETHREX_DEPLOYER_ENV_FILE_PATH=/env/.env
      - ETHREX_DEPLOYER_GENESIS_L1_PATH=${DOCKER_ETHREX_WORKDIR}/fixtures/genesis/l1.json
      - ETHREX_DEPLOYER_GENESIS_L2_PATH=${DOCKER_ETHREX_WORKDIR}/fixtures/genesis/l2.json
      - ETHREX_DEPLOYER_PRIVATE_KEYS_FILE_PATH=${DOCKER_ETHREX_WORKDIR}/fixtures/keys/private_keys_l1.txt
      - ETHREX_DEPLOYER_DEPLOY_RICH=${ETHREX_DEPLOYER_DEPLOY_RICH:-true}
      - ETHREX_L2_RISC0=${ETHREX_L2_RISC0:-false}
      - ETHREX_DEPLOYER_RISC0_VERIFIER_ADDRESS
      - ETHREX_L2_SP1=${ETHREX_L2_SP1:-false}
      - ETHREX_L2_TDX=${ETHREX_L2_TDX:-false}
      - ETHREX_DEPLOYER_TDX_VERIFIER_ADDRESS
      - ETHREX_DEPLOYER_ALIGNED=${ETHREX_DEPLOYER_ALIGNED:-false}
      - ETHREX_SP1_VERIFICATION_KEY_PATH=${DOCKER_ETHREX_WORKDIR}/riscv32im-succinct-zkvm-vk-bn254
      - ETHREX_RISC0_VERIFICATION_KEY_PATH=${DOCKER_ETHREX_WORKDIR}/riscv32im-risc0-vk
      - ETHREX_TDX_DEV_MODE=${ETHREX_TDX_DEV_MODE:-false}
      - ETHREX_ON_CHAIN_PROPOSER_OWNER=0x4417092b70a3e5f10dc504d0947dd256b965fc62
      - ETHREX_BRIDGE_OWNER=0x4417092b70a3e5f10dc504d0947dd256b965fc62
      - ETHREX_BRIDGE_OWNER_PK=${ETHREX_BRIDGE_OWNER_PK:-0x941e103320615d394a55708be13e45994c7d93b932b064dbcb2b511fe3254e2e}
      - ETHREX_DEPLOYER_SEQUENCER_REGISTRY_OWNER=0x4417092b70a3e5f10dc504d0947dd256b965fc62
      - ETHREX_DEPLOYER_DEPLOY_BASED_CONTRACTS=${ETHREX_DEPLOYER_DEPLOY_BASED_CONTRACTS:-false}
      - ETHREX_DEPLOYER_INITIAL_FEE_TOKEN
      - ETHREX_L2_VALIDIUM=${ETHREX_L2_VALIDIUM:-false}
      - COMPILE_CONTRACTS=true
      - ETHREX_USE_COMPILED_GENESIS=true
      - ETHREX_SHARED_BRIDGE_DEPLOY_ROUTER
      - ETHREX_ON_CHAIN_PROPOSER_INCLUSION_MAX_WAIT
    depends_on:
      - ethrex_l1
    entrypoint:
      - /bin/bash
      - -c
      - touch /env/.env; ./ethrex l2 deploy "$0" "$@"
    command: >
      --randomize-contract-deployment

  ethrex_l2:
    container_name: ethrex_l2
    image: "ethrex:main-l2"
    build:
      context: ../../
      args:
        - BUILD_FLAGS=--features l2,l2-sql
    ports:
      # RPC
      - 127.0.0.1:1729:1729
      # Proposer
      - ${ETHREX_PROOF_COORDINATOR_ADDRESS:-127.0.0.1}:3900:3900
    environment:
      # Default values are taken from cmd/ethrex/l2/options.rs defaults.
      - ETHREX_ETH_RPC_URL=http://ethrex_l1:8545
      - ETHREX_L2_VALIDIUM=${ETHREX_L2_VALIDIUM:-false}
      - ETHREX_BLOCK_PRODUCER_BLOCK_TIME=${ETHREX_BLOCK_PRODUCER_BLOCK_TIME:-5000}
      - ETHREX_DEPLOYER_PICO_DEPLOY_VERIFIER=${ETHREX_DEPLOYER_PICO_DEPLOY_VERIFIER:-false}
      - ETHREX_WATCHER_BLOCK_DELAY=${ETHREX_WATCHER_BLOCK_DELAY:-0}
      - ETHREX_BASED=${ETHREX_BASED:-false}
      - ETHREX_BLOCK_PRODUCER_BASE_FEE_VAULT_ADDRESS
      - ETHREX_BLOCK_PRODUCER_OPERATOR_FEE_VAULT_ADDRESS
      - ETHREX_BLOCK_PRODUCER_OPERATOR_FEE_PER_GAS
      - ETHREX_BLOCK_PRODUCER_L1_FEE_VAULT_ADDRESS
      - ETHREX_WATCHER_L1_FEE_VAULT_ADDRESS
      - ETHREX_STATE_UPDATER_SEQUENCER_REGISTRY=${ETHREX_STATE_UPDATER_SEQUENCER_REGISTRY:-0x0000000000000000000000000000000000000000}
      - ETHREX_COMMITTER_COMMIT_TIME=${ETHREX_COMMITTER_COMMIT_TIME:-60000}
      - ETHREX_WATCHER_WATCH_INTERVAL=${ETHREX_WATCHER_WATCH_INTERVAL:-12000}
      - ETHREX_OSAKA_ACTIVATION_TIME=${ETHREX_OSAKA_ACTIVATION_TIME:-1761677592}
      - ETHREX_WATCHER_L2_RPCS
      - ETHREX_WATCHER_L2_CHAIN_IDS
      - ETHREX_WATCHER_ROUTER_ADDRESS
      - ETHREX_LOG_LEVEL
      - ETHREX_GUEST_PROGRAM_ID=${ETHREX_GUEST_PROGRAM_ID:-evm-l2}
    volumes:
      - ../../fixtures/genesis/l2.json:/genesis/l2.json
      - env:/env/
    entrypoint:
      - /bin/bash
      - -c
      - export $(xargs < /env/.env); ./ethrex l2 "$0" "$@"
    # ETHREX_WATCHER_BRIDGE_ADDRESS and ETHREX_COMMITTER_ON_CHAIN_PROPOSER_ADDRESS are set in the .env file by the contract_deployer service.
    command: >
      --network /genesis/l2.json
      --http.addr 0.0.0.0
      --http.port 1729
      --authrpc.port 8552
      --proof-coordinator.addr 0.0.0.0
      --block-producer.coinbase-address 0x0007a881CD95B1484fca47615B64803dad620C8d
      --committer.l1-private-key 0x385c546456b6a603a1cfcaa9ec9494ba4832da08dd6bcf4de9a71e4a01b74924
      --proof-coordinator.l1-private-key 0x39725efee3fb28614de3bacaffe4cc4bd8c436257e2c8bb887c4b5c4be45e76d
      --no-monitor
    depends_on:
      contract_deployer:
        condition: service_completed_successfully

  ethrex_prover:
    container_name: ethrex_prover
    image: "ethrex:main-l2"
    build:
      context: ../../
      args:
        - BUILD_FLAGS=--features l2,l2-sql
    command: >
      l2 prover
      --backend exec
      --proof-coordinators tcp://ethrex_l2:3900
    depends_on:
      - ethrex_l2
