services:
  web3signer:
    restart: always
    container_name: web3signer
    image: "consensys/web3signer"
    ports:
      # API
      - 0.0.0.0:9000:9000
    volumes:
      - ../../fixtures/keys:/keys
    command: "--http-host-allowlist=* --key-store-path=/keys eth1 --chain-id=1729"

  tokamak-app-l2:
    command: >
      --network /genesis/l2.json
      --http.addr 0.0.0.0
      --http.port 1729
      --authrpc.port 8552
      --proof-coordinator.addr 0.0.0.0
      --block-producer.coinbase-address 0x0007a881CD95B1484fca47615B64803dad620C8d
      --block-producer.base-fee-vault-address 0x000c0d6b7c4516a5b274c51ea331a9410fe69127
      --committer.remote-signer-url http://web3signer:9000
      --committer.remote-signer-public-key 02eadbea0cdb17fda8d56fc9c51df8a6158c2ab157aabf2ca57c3a32cd69f98bbc
      --proof-coordinator.remote-signer-url http://web3signer:9000
      --proof-coordinator.remote-signer-public-key 029a87812d21330c485e2ab11fbbcc875fd3ecda9e74c3964d8de9a95560b64f21
      --no-monitor
